--------------------------------------------------------
--  File created - Saturday-May-27-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_HOADON
--------------------------------------------------------

   CREATE SEQUENCE  "CHQTCSDL"."SEQ_HOADON"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 50 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_KHACHHANG
--------------------------------------------------------

   CREATE SEQUENCE  "CHQTCSDL"."SEQ_KHACHHANG"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PHIEUNHAP
--------------------------------------------------------

   CREATE SEQUENCE  "CHQTCSDL"."SEQ_PHIEUNHAP"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SANPHAM
--------------------------------------------------------

   CREATE SEQUENCE  "CHQTCSDL"."SEQ_SANPHAM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 42 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CTHD
--------------------------------------------------------

  CREATE TABLE "CHQTCSDL"."CTHD" 
   (	"SOHD" VARCHAR2(10 BYTE), 
	"MASP" VARCHAR2(10 BYTE), 
	"DONGIA" NUMBER(10,2), 
	"SOLUONG" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT INSERT ON "CHQTCSDL"."CTHD" TO "ROLE_CHUCUAHANG";
  GRANT SELECT ON "CHQTCSDL"."CTHD" TO "ROLE_CHUCUAHANG";
  GRANT UPDATE ON "CHQTCSDL"."CTHD" TO "ROLE_CHUCUAHANG";
  GRANT DELETE ON "CHQTCSDL"."CTHD" TO "CHUCUAHANG";
  GRANT INSERT ON "CHQTCSDL"."CTHD" TO "CHUCUAHANG";
  GRANT UPDATE ON "CHQTCSDL"."CTHD" TO "CHUCUAHANG";
  GRANT DELETE ON "CHQTCSDL"."CTHD" TO "ROLE_CHUCUAHANG";
  GRANT DELETE ON "CHQTCSDL"."CTHD" TO "ROLE_NHANVIENBANHANG";
  GRANT INSERT ON "CHQTCSDL"."CTHD" TO "ROLE_NHANVIENBANHANG";
  GRANT SELECT ON "CHQTCSDL"."CTHD" TO "ROLE_NHANVIENBANHANG";
  GRANT UPDATE ON "CHQTCSDL"."CTHD" TO "ROLE_NHANVIENBANHANG";
--------------------------------------------------------
--  DDL for Table CTPN
--------------------------------------------------------

  CREATE TABLE "CHQTCSDL"."CTPN" 
   (	"MAPN" VARCHAR2(10 BYTE), 
	"MASP" VARCHAR2(10 BYTE), 
	"SLNHAP" NUMBER, 
	"DONGIANHAP" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "CHQTCSDL"."CTPN" TO "ROLE_CHUCUAHANG";
  GRANT INSERT ON "CHQTCSDL"."CTPN" TO "ROLE_CHUCUAHANG";
  GRANT SELECT ON "CHQTCSDL"."CTPN" TO "ROLE_CHUCUAHANG";
  GRANT UPDATE ON "CHQTCSDL"."CTPN" TO "ROLE_CHUCUAHANG";
  GRANT DELETE ON "CHQTCSDL"."CTPN" TO "ROLE_NHANVIENNHAPHANG";
  GRANT INSERT ON "CHQTCSDL"."CTPN" TO "ROLE_NHANVIENNHAPHANG";
  GRANT SELECT ON "CHQTCSDL"."CTPN" TO "ROLE_NHANVIENNHAPHANG";
  GRANT UPDATE ON "CHQTCSDL"."CTPN" TO "ROLE_NHANVIENNHAPHANG";
--------------------------------------------------------
--  DDL for Table HOADON
--------------------------------------------------------

  CREATE TABLE "CHQTCSDL"."HOADON" 
   (	"SOHD" VARCHAR2(10 BYTE), 
	"NGAY" DATE, 
	"MAKH" VARCHAR2(10 BYTE), 
	"MANV" VARCHAR2(10 BYTE), 
	"TONGTG" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "CHQTCSDL"."HOADON" TO "ROLE_CHUCUAHANG";
  GRANT INSERT ON "CHQTCSDL"."HOADON" TO "ROLE_CHUCUAHANG";
  GRANT SELECT ON "CHQTCSDL"."HOADON" TO "ROLE_CHUCUAHANG";
  GRANT UPDATE ON "CHQTCSDL"."HOADON" TO "ROLE_CHUCUAHANG";
  GRANT DELETE ON "CHQTCSDL"."HOADON" TO "ROLE_NHANVIENBANHANG";
  GRANT INSERT ON "CHQTCSDL"."HOADON" TO "ROLE_NHANVIENBANHANG";
  GRANT SELECT ON "CHQTCSDL"."HOADON" TO "ROLE_NHANVIENBANHANG";
  GRANT UPDATE ON "CHQTCSDL"."HOADON" TO "ROLE_NHANVIENBANHANG";
--------------------------------------------------------
--  DDL for Table KHACHHANG
--------------------------------------------------------

  CREATE TABLE "CHQTCSDL"."KHACHHANG" 
   (	"MAKH" VARCHAR2(10 BYTE), 
	"HOTEN" VARCHAR2(50 BYTE), 
	"DIACHI" VARCHAR2(100 BYTE), 
	"SODT" VARCHAR2(12 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"DOANHSO" NUMBER(10,2) DEFAULT 0, 
	"DIEMTICHLUY" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "CHQTCSDL"."KHACHHANG" TO "ROLE_CHUCUAHANG";
  GRANT INSERT ON "CHQTCSDL"."KHACHHANG" TO "ROLE_CHUCUAHANG";
  GRANT SELECT ON "CHQTCSDL"."KHACHHANG" TO "ROLE_CHUCUAHANG";
  GRANT UPDATE ON "CHQTCSDL"."KHACHHANG" TO "ROLE_CHUCUAHANG";
  GRANT DELETE ON "CHQTCSDL"."KHACHHANG" TO "ROLE_NHANVIENBANHANG";
  GRANT INSERT ON "CHQTCSDL"."KHACHHANG" TO "ROLE_NHANVIENBANHANG";
  GRANT SELECT ON "CHQTCSDL"."KHACHHANG" TO "ROLE_NHANVIENBANHANG";
  GRANT UPDATE ON "CHQTCSDL"."KHACHHANG" TO "ROLE_NHANVIENBANHANG";
--------------------------------------------------------
--  DDL for Table LOAISANPHAM
--------------------------------------------------------

  CREATE TABLE "CHQTCSDL"."LOAISANPHAM" 
   (	"MALOAI" VARCHAR2(10 BYTE), 
	"TENLOAI" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "CHQTCSDL"."LOAISANPHAM" TO "ROLE_CHUCUAHANG";
  GRANT INSERT ON "CHQTCSDL"."LOAISANPHAM" TO "ROLE_CHUCUAHANG";
  GRANT SELECT ON "CHQTCSDL"."LOAISANPHAM" TO "ROLE_CHUCUAHANG";
  GRANT UPDATE ON "CHQTCSDL"."LOAISANPHAM" TO "ROLE_CHUCUAHANG";
  GRANT SELECT ON "CHQTCSDL"."LOAISANPHAM" TO "ROLE_NHANVIENNHAPHANG";
  GRANT SELECT ON "CHQTCSDL"."LOAISANPHAM" TO "ROLE_NHANVIENBANHANG";
--------------------------------------------------------
--  DDL for Table NHACUNGCAP
--------------------------------------------------------

  CREATE TABLE "CHQTCSDL"."NHACUNGCAP" 
   (	"MANCC" VARCHAR2(10 BYTE), 
	"TENNCC" VARCHAR2(50 BYTE), 
	"DIACHI" VARCHAR2(100 BYTE), 
	"SDT" VARCHAR2(12 BYTE), 
	"QUOCGIA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "CHQTCSDL"."NHACUNGCAP" TO "ROLE_CHUCUAHANG";
  GRANT INSERT ON "CHQTCSDL"."NHACUNGCAP" TO "ROLE_CHUCUAHANG";
  GRANT SELECT ON "CHQTCSDL"."NHACUNGCAP" TO "ROLE_CHUCUAHANG";
  GRANT UPDATE ON "CHQTCSDL"."NHACUNGCAP" TO "ROLE_CHUCUAHANG";
  GRANT DELETE ON "CHQTCSDL"."NHACUNGCAP" TO "ROLE_NHANVIENNHAPHANG";
  GRANT INSERT ON "CHQTCSDL"."NHACUNGCAP" TO "ROLE_NHANVIENNHAPHANG";
  GRANT SELECT ON "CHQTCSDL"."NHACUNGCAP" TO "ROLE_NHANVIENNHAPHANG";
  GRANT UPDATE ON "CHQTCSDL"."NHACUNGCAP" TO "ROLE_NHANVIENNHAPHANG";
--------------------------------------------------------
--  DDL for Table NHANVIEN
--------------------------------------------------------

  CREATE TABLE "CHQTCSDL"."NHANVIEN" 
   (	"MANV" VARCHAR2(10 BYTE), 
	"HOTEN" VARCHAR2(50 BYTE), 
	"NGAYSINH" DATE, 
	"GIOITINH" VARCHAR2(10 BYTE), 
	"SDT" VARCHAR2(12 BYTE), 
	"DIACHI" VARCHAR2(100 BYTE), 
	"LUONG" NUMBER(10,2), 
	"NGAYLV" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "CHQTCSDL"."NHANVIEN" TO "ROLE_CHUCUAHANG";
  GRANT INSERT ON "CHQTCSDL"."NHANVIEN" TO "ROLE_CHUCUAHANG";
  GRANT SELECT ON "CHQTCSDL"."NHANVIEN" TO "ROLE_CHUCUAHANG";
  GRANT UPDATE ON "CHQTCSDL"."NHANVIEN" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Table PHIEUNHAP
--------------------------------------------------------

  CREATE TABLE "CHQTCSDL"."PHIEUNHAP" 
   (	"MAPN" VARCHAR2(10 BYTE), 
	"NGAYNHAP" DATE, 
	"MANCC" VARCHAR2(10 BYTE), 
	"MANV" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "CHQTCSDL"."PHIEUNHAP" TO "ROLE_CHUCUAHANG";
  GRANT INSERT ON "CHQTCSDL"."PHIEUNHAP" TO "ROLE_CHUCUAHANG";
  GRANT SELECT ON "CHQTCSDL"."PHIEUNHAP" TO "ROLE_CHUCUAHANG";
  GRANT UPDATE ON "CHQTCSDL"."PHIEUNHAP" TO "ROLE_CHUCUAHANG";
  GRANT DELETE ON "CHQTCSDL"."PHIEUNHAP" TO "ROLE_NHANVIENNHAPHANG";
  GRANT INSERT ON "CHQTCSDL"."PHIEUNHAP" TO "ROLE_NHANVIENNHAPHANG";
  GRANT SELECT ON "CHQTCSDL"."PHIEUNHAP" TO "ROLE_NHANVIENNHAPHANG";
  GRANT UPDATE ON "CHQTCSDL"."PHIEUNHAP" TO "ROLE_NHANVIENNHAPHANG";
--------------------------------------------------------
--  DDL for Table QUANTRI
--------------------------------------------------------

  CREATE TABLE "CHQTCSDL"."QUANTRI" 
   (	"MAQT" VARCHAR2(10 BYTE), 
	"TAIKHOAN" VARCHAR2(20 BYTE), 
	"MATKHAU" VARCHAR2(200 BYTE), 
	"VAITRO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "CHQTCSDL"."QUANTRI" TO "ROLE_CHUCUAHANG";
  GRANT INSERT ON "CHQTCSDL"."QUANTRI" TO "ROLE_CHUCUAHANG";
  GRANT SELECT ON "CHQTCSDL"."QUANTRI" TO "ROLE_CHUCUAHANG";
  GRANT UPDATE ON "CHQTCSDL"."QUANTRI" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Table SANPHAM
--------------------------------------------------------

  CREATE TABLE "CHQTCSDL"."SANPHAM" 
   (	"MASP" VARCHAR2(10 BYTE), 
	"TENSP" VARCHAR2(50 BYTE), 
	"SLTON" NUMBER DEFAULT 0, 
	"DVT" VARCHAR2(20 BYTE), 
	"DONGIA" NUMBER(10,2), 
	"LOAISP" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "CHQTCSDL"."SANPHAM" TO "ROLE_CHUCUAHANG";
  GRANT INSERT ON "CHQTCSDL"."SANPHAM" TO "ROLE_CHUCUAHANG";
  GRANT SELECT ON "CHQTCSDL"."SANPHAM" TO "ROLE_CHUCUAHANG";
  GRANT UPDATE ON "CHQTCSDL"."SANPHAM" TO "ROLE_CHUCUAHANG";
  GRANT SELECT ON "CHQTCSDL"."SANPHAM" TO "ROLE_NHANVIENNHAPHANG";
  GRANT SELECT ON "CHQTCSDL"."SANPHAM" TO "ROLE_NHANVIENBANHANG";
--------------------------------------------------------
--  DDL for View VIEW_DANHSACHHOADON
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CHQTCSDL"."VIEW_DANHSACHHOADON" ("SOHD", "NGAY", "HOTENKH", "HOTENNV", "TONGTG") AS 
  SELECT SOHD, NGAY, KH.HOTEN AS HOTENKH, NV.HOTEN AS HOTENNV, TONGTG 
    FROM HOADON HD 
    JOIN KHACHHANG KH ON HD.MAKH = KH.MAKH
    JOIN NHANVIEN NV ON HD.MANV = NV.MANV
;
--------------------------------------------------------
--  DDL for View VIEW_DANHSACHPHIEUNHAP
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CHQTCSDL"."VIEW_DANHSACHPHIEUNHAP" ("MAPN", "NGAYNHAP", "TONGTIENNHAP", "TENNCC", "TENNV") AS 
  SELECT PN.MAPN, PN.NGAYNHAP, COALESCE(SUM(CT.DONGIANHAP * CT.SLNHAP), 0) AS TONGTIENNHAP, NCC.TENNCC, NV.HOTEN AS TENNV
    FROM PHIEUNHAP PN
    JOIN NHACUNGCAP NCC ON PN.MANCC = NCC.MANCC
    JOIN NHANVIEN NV ON PN.MANV = NV.MANV
    LEFT JOIN CTPN CT ON CT.MAPN = PN.MAPN
    GROUP BY PN.MAPN, PN.NGAYNHAP, NCC.TENNCC, NV.HOTEN
    ORDER BY PN.NGAYNHAP DESC
;
--------------------------------------------------------
--  DDL for View VIEW_DANHSACHSANPHAM
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CHQTCSDL"."VIEW_DANHSACHSANPHAM" ("MASP", "TENSP", "SLNHAP", "SLTON", "SLBAN", "DVT", "DONGIA", "LOAISP") AS 
  SELECT MASP, TENSP, FUNC_DEMSOLUONGSP_CTPN(MASP) AS SLNHAP,
            SLTON, FUNC_SoLuongSanPhamBanDuoc(MASP) as SLBAN, 
            DVT, DONGIA , LOAISANPHAM.TENLOAI AS LOAISP
    FROM SANPHAM, LOAISANPHAM
    WHERE SANPHAM.LOAISP = LOAISANPHAM.MALOAI
;
--------------------------------------------------------
--  DDL for View VIEW_DS_KHACHHANG
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CHQTCSDL"."VIEW_DS_KHACHHANG" ("MAKH", "HOTEN", "DIACHI", "SODT", "EMAIL", "SOHDSOHUU", "DOANHSO", "DIEMTICHLUY") AS 
  SELECT MAKH, HOTEN, DIACHI, SODT, EMAIL, 
            FUNC_DEMSOHOADONCUAKH(MAKH) AS SOHDSOHUU, DOANHSO, DIEMTICHLUY
    FROM KHACHHANG
;
--------------------------------------------------------
--  DDL for View VIEW_HOATDONGCUANV
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CHQTCSDL"."VIEW_HOATDONGCUANV" ("MANV", "HOTEN", "GIOITINH", "SDT", "DIACHI", "LUONG", "SOHDDALAP", "SOPHIEUDALAP", "LOINHUAN") AS 
  SELECT MANV, HOTEN, GIOITINH, SDT, DIACHI, LUONG, PKG_HOATDONG_NHANVIEN.FUNC_SOHD(MANV) AS SOHDDALAP,
            PKG_HOATDONG_NHANVIEN.FUNC_SOPN(MANV) AS SOPHIEUDALAP,
            PKG_HOATDONG_NHANVIEN.FUNC_DOANHTHU(MANV) AS LOINHUAN
    FROM NHANVIEN
;
--------------------------------------------------------
--  DDL for View VIEW_LAIXUATCUASANPHAM
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CHQTCSDL"."VIEW_LAIXUATCUASANPHAM" ("MASP", "TENSP", "SOLUONG", "LAIXUAT") AS 
  SELECT MASP, TENSP, FUNC_SoLuongSanPhamBanDuoc(MASP) as soluong, 
        func_TinhLaiCuaSP(MASP) as laixuat 
FROM SANPHAM
;
REM INSERTING into CHQTCSDL.CTHD
SET DEFINE OFF;
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD20','SP19',9120,1);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD22','SP19',9120,2);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD000040','SP11',12650,3);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD01','SP31',11400,10);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD01','SP48',215400,5);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD02','SP11',13800,5);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD02','SP31',11400,2);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD03','SP07',9120,1);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD03','SP21',29880,5);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD04','SP33',13200,6);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD04','SP44',44760,2);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD05','SP27',27720,3);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD06','SP15',29880,8);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD07','SP16',66480,3);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD07','SP35',69120,2);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD07','SP39',10560,1);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD10','SP16',66480,2);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD10','SP15',29880,4);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD11','SP07',9120,2);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD11','SP08',46200,1);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD12','SP02',17880,4);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD13','SP04',34680,3);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD13','SP05',13800,1);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD14','SP06',25800,2);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD15','SP07',9120,1);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD16','SP10',66480,5);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD16','SP19',9120,2);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD17','SP21',29880,1);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD17','SP38',110400,2);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD18','SP40',67200,1);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD19','SP18',25800,3);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD19','SP22',66480,4);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD19','SP37',186000,2);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD20','SP09',29880,1);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD20','SP13',9120,4);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD23','SP50',29700,4);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD23','SP19',8360,2);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD23','SP06',23650,4);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD08','SP23',37400,13);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD05','SP17',12650,10);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD000002','SP000002',18700,3);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD000002','SP000001',14300,5);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD000004','SP10',60940,3);
Insert into CHQTCSDL.CTHD (SOHD,MASP,DONGIA,SOLUONG) values ('HD000021','SP000002',18700,3);
REM INSERTING into CHQTCSDL.CTPN
SET DEFINE OFF;
Insert into CHQTCSDL.CTPN (MAPN,MASP,SLNHAP,DONGIANHAP) values ('PN01','SP04',13,12000);
Insert into CHQTCSDL.CTPN (MAPN,MASP,SLNHAP,DONGIANHAP) values ('PN01','SP02',13,14000);
Insert into CHQTCSDL.CTPN (MAPN,MASP,SLNHAP,DONGIANHAP) values ('PN02','SP33',23,15000);
Insert into CHQTCSDL.CTPN (MAPN,MASP,SLNHAP,DONGIANHAP) values ('PN03','SP05',10,20000);
Insert into CHQTCSDL.CTPN (MAPN,MASP,SLNHAP,DONGIANHAP) values ('PN13','SP02',10,11000);
Insert into CHQTCSDL.CTPN (MAPN,MASP,SLNHAP,DONGIANHAP) values ('PN13','SP23',12,8000);
Insert into CHQTCSDL.CTPN (MAPN,MASP,SLNHAP,DONGIANHAP) values ('PN11','SP38',13,20000);
Insert into CHQTCSDL.CTPN (MAPN,MASP,SLNHAP,DONGIANHAP) values ('PN000001','SP000002',21,15000);
Insert into CHQTCSDL.CTPN (MAPN,MASP,SLNHAP,DONGIANHAP) values ('PN000004','SP39',11,60000);
REM INSERTING into CHQTCSDL.HOADON
SET DEFINE OFF;
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD01',to_date('01-MAY-23','DD-MON-RR'),'KH02','NV03',1191000);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD02',to_date('01-MAY-23','DD-MON-RR'),'KH03','NV02',91800);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD03',to_date('01-MAY-23','DD-MON-RR'),'KH04','NV05',158520);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD04',to_date('01-MAY-23','DD-MON-RR'),'KH01','NV02',168720);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD05',to_date('01-MAY-23','DD-MON-RR'),'KH06','NV01',209660);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD06',to_date('01-MAY-23','DD-MON-RR'),'KH07','NV04',239040);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD07',to_date('02-MAY-23','DD-MON-RR'),'KH08','NV03',348240);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD08',to_date('02-MAY-23','DD-MON-RR'),'KH09','NV01',486200);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD24',to_date('12-MAY-23','DD-MON-RR'),'KH11','NV07',null);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD10',to_date('02-MAY-23','DD-MON-RR'),'KH01','NV04',252480);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD11',to_date('02-MAY-23','DD-MON-RR'),'KH03','NV02',64440);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD12',to_date('02-MAY-23','DD-MON-RR'),'KH08','NV01',71520);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD13',to_date('02-MAY-23','DD-MON-RR'),'KH05','NV01',117840);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD14',to_date('03-MAY-23','DD-MON-RR'),'KH06','NV05',51600);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD15',to_date('03-MAY-23','DD-MON-RR'),'KH09','NV02',9120);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD16',to_date('03-MAY-23','DD-MON-RR'),'KH10','NV03',350640);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD17',to_date('03-MAY-23','DD-MON-RR'),'KH07','NV04',250680);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD18',to_date('03-MAY-23','DD-MON-RR'),'KH02','NV03',67200);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD19',to_date('03-MAY-23','DD-MON-RR'),'KH04','NV03',715320);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD20',to_date('10-MAY-23','DD-MON-RR'),'KH07','NV10',75480);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD000040',to_date('19-MAY-23','DD-MON-RR'),'KH005','NV11',37950);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD23',to_date('12-MAY-23','DD-MON-RR'),'KH02','NV05',230120);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD000002',to_date('11-MAY-23','DD-MON-RR'),'KH02','NV03',127600);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD000003',to_date('14-MAY-23','DD-MON-RR'),'KH05','NV10',0);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD000039',to_date('19-MAY-23','DD-MON-RR'),'KH03','NV08',0);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD22',to_date('11-MAY-23','DD-MON-RR'),'KH08','NV02',18240);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD000004',to_date('14-MAY-23','DD-MON-RR'),'KH13','NV03',182820);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD000021',to_date('19-MAY-23','DD-MON-RR'),'KH002','NV06',56100);
Insert into CHQTCSDL.HOADON (SOHD,NGAY,MAKH,MANV,TONGTG) values ('HD000048',to_date('23-MAY-23','DD-MON-RR'),'KH01','NV01',0);
REM INSERTING into CHQTCSDL.KHACHHANG
SET DEFINE OFF;
Insert into CHQTCSDL.KHACHHANG (MAKH,HOTEN,DIACHI,SODT,EMAIL,DOANHSO,DIEMTICHLUY) values ('KH12','Masa ','312 New York','012341231','masa@gmail.com',0,0);
Insert into CHQTCSDL.KHACHHANG (MAKH,HOTEN,DIACHI,SODT,EMAIL,DOANHSO,DIEMTICHLUY) values ('KH01','?? Anh Duy','828 S? V?n H?nh','01111111','doanhduy@gmail.com',421200,0);
Insert into CHQTCSDL.KHACHHANG (MAKH,HOTEN,DIACHI,SODT,EMAIL,DOANHSO,DIEMTICHLUY) values ('KH02','?? Y?n Nhi','171 L� Th??ng Ki?t','02222222','doyennhi@yahoo.com',1615920,0);
Insert into CHQTCSDL.KHACHHANG (MAKH,HOTEN,DIACHI,SODT,EMAIL,DOANHSO,DIEMTICHLUY) values ('KH03','Ph?m Minh Ng?c','123 L� Ch�nh Th?ng','03333333','minhngoccute@outlook.com',156240,0);
Insert into CHQTCSDL.KHACHHANG (MAKH,HOTEN,DIACHI,SODT,EMAIL,DOANHSO,DIEMTICHLUY) values ('KH04','Ph?m Ng?c M?','33 T�n Quang Tho?i','04444444','ngocmydangiu@edu.vn',873840,0);
Insert into CHQTCSDL.KHACHHANG (MAKH,HOTEN,DIACHI,SODT,EMAIL,DOANHSO,DIEMTICHLUY) values ('KH05','Nguy?n Ph??ng Nghi','66 ???ng 3 th�ng 2','05555555','phuongnghi@mail.edu.vn',117840,0);
Insert into CHQTCSDL.KHACHHANG (MAKH,HOTEN,DIACHI,SODT,EMAIL,DOANHSO,DIEMTICHLUY) values ('KH06','Tran Mesi','Trung t�m ph?n m�m Quang Trung','06666666','tranmesimodel@st.edu.vn',261260,0);
Insert into CHQTCSDL.KHACHHANG (MAKH,HOTEN,DIACHI,SODT,EMAIL,DOANHSO,DIEMTICHLUY) values ('KH07','Tr?n Ng?c Duy�n','K� t�c x� ??i h?c qu?c gia','07777777','ngocduyenxinhdep@gmail.com',565200,0);
Insert into CHQTCSDL.KHACHHANG (MAKH,HOTEN,DIACHI,SODT,EMAIL,DOANHSO,DIEMTICHLUY) values ('KH08','Ph?m Th�nh Danh','321 C�ch m?ng th�ng 8','08888888','danhhust@yahoo.com',438000,0);
Insert into CHQTCSDL.KHACHHANG (MAKH,HOTEN,DIACHI,SODT,EMAIL,DOANHSO,DIEMTICHLUY) values ('KH09','Tr?n Huy?n Kh??ng','02 Tho?i Ng?c H?u','09999999','huyenkhuong@huflit.com',495320,0);
Insert into CHQTCSDL.KHACHHANG (MAKH,HOTEN,DIACHI,SODT,EMAIL,DOANHSO,DIEMTICHLUY) values ('KH10','Nguy?n L?ng Nh? Qu?nh','100 Nguy?n Th�i S?n','01010101','quynhsoi@mail.com.vn',350640,0);
Insert into CHQTCSDL.KHACHHANG (MAKH,HOTEN,DIACHI,SODT,EMAIL,DOANHSO,DIEMTICHLUY) values ('KH11','Nguy?n Th�y D??ng','25 Tr??ng Chinh','01212122','thuyduongnguyen@outlook.com',null,0);
Insert into CHQTCSDL.KHACHHANG (MAKH,HOTEN,DIACHI,SODT,EMAIL,DOANHSO,DIEMTICHLUY) values ('KH002','Nguy?n Nh?t �nh','Trung t�m ph?n m?m Quang Trung','098214567','example@outlook.com',56100,0);
Insert into CHQTCSDL.KHACHHANG (MAKH,HOTEN,DIACHI,SODT,EMAIL,DOANHSO,DIEMTICHLUY) values ('KH13','Tr?n Lan Anh','22 C�ch M?ng Th�ng 10 Nga','098212321',null,182820,0);
Insert into CHQTCSDL.KHACHHANG (MAKH,HOTEN,DIACHI,SODT,EMAIL,DOANHSO,DIEMTICHLUY) values ('KH005','Ki?u My','113 Boston','032212324','example2@gmail.com',37950,0);
REM INSERTING into CHQTCSDL.LOAISANPHAM
SET DEFINE OFF;
Insert into CHQTCSDL.LOAISANPHAM (MALOAI,TENLOAI) values ('L01','Rau c? t??i');
Insert into CHQTCSDL.LOAISANPHAM (MALOAI,TENLOAI) values ('L02','Tr�i c�y');
Insert into CHQTCSDL.LOAISANPHAM (MALOAI,TENLOAI) values ('L03','Th?t, Tr?ng');
Insert into CHQTCSDL.LOAISANPHAM (MALOAI,TENLOAI) values ('L04','Th?c ?n ch? bi?n');
Insert into CHQTCSDL.LOAISANPHAM (MALOAI,TENLOAI) values ('L05','Th?c ph?m ?�ng, m�t');
Insert into CHQTCSDL.LOAISANPHAM (MALOAI,TENLOAI) values ('L06','S?a, th?c ph?m t? s?a');
Insert into CHQTCSDL.LOAISANPHAM (MALOAI,TENLOAI) values ('L07','Th?c u?ng');
REM INSERTING into CHQTCSDL.NHACUNGCAP
SET DEFINE OFF;
Insert into CHQTCSDL.NHACUNGCAP (MANCC,TENNCC,DIACHI,SDT,QUOCGIA) values ('N01','Th�nh Nam Food','168/42 DX006 , KP 8, P. Ph� M?, Th? D?u M?t','0971001002','Vi?t Nam');
Insert into CHQTCSDL.NHACUNGCAP (MANCC,TENNCC,DIACHI,SDT,QUOCGIA) values ('N02','Th?c ph?m H?u Ngh? ','9C10 KDC Nam Long, H� Huy Gi�p, KP3','0901892899','Vi?t Nam');
Insert into CHQTCSDL.NHACUNGCAP (MANCC,TENNCC,DIACHI,SDT,QUOCGIA) values ('N03','Sannest','123 Newyork','012345678','H�n Qu?c');
Insert into CHQTCSDL.NHACUNGCAP (MANCC,TENNCC,DIACHI,SDT,QUOCGIA) values ('N05','Authenic Asia','33 B?ng C?c','03421442','Th�i Lan');
Insert into CHQTCSDL.NHACUNGCAP (MANCC,TENNCC,DIACHI,SDT,QUOCGIA) values ('N06','Ogannic','44 Ohio','09891231','M?');
Insert into CHQTCSDL.NHACUNGCAP (MANCC,TENNCC,DIACHI,SDT,QUOCGIA) values ('N07','Nutrition','Tottenham, Lu�n ?�n','03123146','V??ng Qu?c Anh');
Insert into CHQTCSDL.NHACUNGCAP (MANCC,TENNCC,DIACHI,SDT,QUOCGIA) values ('N8','M? Anh','T�n S?n, T�n Qu�, T�n K?','012312312','�');
REM INSERTING into CHQTCSDL.NHANVIEN
SET DEFINE OFF;
Insert into CHQTCSDL.NHANVIEN (MANV,HOTEN,NGAYSINH,GIOITINH,SDT,DIACHI,LUONG,NGAYLV) values ('NV01','Chris Do',to_date('14-NOV-01','DD-MON-RR'),'Nam','09090909','123 T?n H?i',9000000,to_date('02-DEC-20','DD-MON-RR'));
Insert into CHQTCSDL.NHANVIEN (MANV,HOTEN,NGAYSINH,GIOITINH,SDT,DIACHI,LUONG,NGAYLV) values ('NV02','Francis Xavier',to_date('02-MAY-02','DD-MON-RR'),'Nam','08080808','345 B?n Nh� R?ng',8000000,to_date('06-FEB-22','DD-MON-RR'));
Insert into CHQTCSDL.NHANVIEN (MANV,HOTEN,NGAYSINH,GIOITINH,SDT,DIACHI,LUONG,NGAYLV) values ('NV03','Peter Pham',to_date('09-JUL-03','DD-MON-RR'),'Nam','07070707','567 T�n Th?t Thuy?t',7500000,to_date('08-DEC-22','DD-MON-RR'));
Insert into CHQTCSDL.NHANVIEN (MANV,HOTEN,NGAYSINH,GIOITINH,SDT,DIACHI,LUONG,NGAYLV) values ('NV04','Nana Tran',to_date('01-DEC-04','DD-MON-RR'),'N?','06060606','789 Nguy?n ?�nh Chi?u',10000000,to_date('04-JAN-22','DD-MON-RR'));
Insert into CHQTCSDL.NHANVIEN (MANV,HOTEN,NGAYSINH,GIOITINH,SDT,DIACHI,LUONG,NGAYLV) values ('NV05','Maria Vu',to_date('19-SEP-02','DD-MON-RR'),'N?','05050505','910 H? Xu�n H??ng	',7000000,to_date('01-DEC-22','DD-MON-RR'));
Insert into CHQTCSDL.NHANVIEN (MANV,HOTEN,NGAYSINH,GIOITINH,SDT,DIACHI,LUONG,NGAYLV) values ('NV06','Oriana Nguyen',to_date('27-JUN-99','DD-MON-RR'),'N?','04040404','1011 Pasteur',6000000,to_date('28-MAR-21','DD-MON-RR'));
Insert into CHQTCSDL.NHANVIEN (MANV,HOTEN,NGAYSINH,GIOITINH,SDT,DIACHI,LUONG,NGAYLV) values ('NV07','Belle Huynh',to_date('30-AUG-03','DD-MON-RR'),'N?','03030303','1122 Nguy?n Th? Minh Khai	',8000000,to_date('12-JUL-22','DD-MON-RR'));
Insert into CHQTCSDL.NHANVIEN (MANV,HOTEN,NGAYSINH,GIOITINH,SDT,DIACHI,LUONG,NGAYLV) values ('NV08','Tracy Nguyen',to_date('04-JAN-02','DD-MON-RR'),'N?','02020202','2233 Chu M?nh Chinh',11000000,to_date('08-DEC-22','DD-MON-RR'));
Insert into CHQTCSDL.NHANVIEN (MANV,HOTEN,NGAYSINH,GIOITINH,SDT,DIACHI,LUONG,NGAYLV) values ('NV09','Partrick Pham',to_date('11-JUL-03','DD-MON-RR'),'Nam','01010101','3344 C�ng Tr??ng Paris	',12000000,to_date('28-JUN-22','DD-MON-RR'));
Insert into CHQTCSDL.NHANVIEN (MANV,HOTEN,NGAYSINH,GIOITINH,SDT,DIACHI,LUONG,NGAYLV) values ('NV10','Andrew Huynh',to_date('31-JUL-01','DD-MON-RR'),'Nam','01020304','4455 Yersin',9500000,to_date('03-MAY-23','DD-MON-RR'));
Insert into CHQTCSDL.NHANVIEN (MANV,HOTEN,NGAYSINH,GIOITINH,SDT,DIACHI,LUONG,NGAYLV) values ('NV11','Lan Nguy�n',to_date('01-JUN-01','DD-MON-RR'),'N?','0961618528','Halifax, V??ng Qu?c Anh',7000000,to_date('05-MAY-23','DD-MON-RR'));
REM INSERTING into CHQTCSDL.PHIEUNHAP
SET DEFINE OFF;
Insert into CHQTCSDL.PHIEUNHAP (MAPN,NGAYNHAP,MANCC,MANV) values ('PN12',to_date('10-MAY-23','DD-MON-RR'),'N06','NV10');
Insert into CHQTCSDL.PHIEUNHAP (MAPN,NGAYNHAP,MANCC,MANV) values ('PN01',to_date('07-APR-23','DD-MON-RR'),'N02','NV06');
Insert into CHQTCSDL.PHIEUNHAP (MAPN,NGAYNHAP,MANCC,MANV) values ('PN02',to_date('11-JAN-23','DD-MON-RR'),'N01','NV06');
Insert into CHQTCSDL.PHIEUNHAP (MAPN,NGAYNHAP,MANCC,MANV) values ('PN03',to_date('09-AUG-23','DD-MON-RR'),'N07','NV02');
Insert into CHQTCSDL.PHIEUNHAP (MAPN,NGAYNHAP,MANCC,MANV) values ('PN04',to_date('01-MAR-23','DD-MON-RR'),'N05','NV07');
Insert into CHQTCSDL.PHIEUNHAP (MAPN,NGAYNHAP,MANCC,MANV) values ('PN05',to_date('01-MAY-23','DD-MON-RR'),'N03','NV08');
Insert into CHQTCSDL.PHIEUNHAP (MAPN,NGAYNHAP,MANCC,MANV) values ('PN06',to_date('02-MAY-23','DD-MON-RR'),'N06','NV06');
Insert into CHQTCSDL.PHIEUNHAP (MAPN,NGAYNHAP,MANCC,MANV) values ('PN07',to_date('02-MAY-23','DD-MON-RR'),'N07','NV07');
Insert into CHQTCSDL.PHIEUNHAP (MAPN,NGAYNHAP,MANCC,MANV) values ('PN08',to_date('03-MAY-23','DD-MON-RR'),'N03','NV10');
Insert into CHQTCSDL.PHIEUNHAP (MAPN,NGAYNHAP,MANCC,MANV) values ('PN09',to_date('03-MAY-23','DD-MON-RR'),'N02','NV08');
Insert into CHQTCSDL.PHIEUNHAP (MAPN,NGAYNHAP,MANCC,MANV) values ('PN10',to_date('03-MAY-23','DD-MON-RR'),'N07','NV07');
Insert into CHQTCSDL.PHIEUNHAP (MAPN,NGAYNHAP,MANCC,MANV) values ('PN11',to_date('10-MAY-23','DD-MON-RR'),'N01','NV09');
Insert into CHQTCSDL.PHIEUNHAP (MAPN,NGAYNHAP,MANCC,MANV) values ('PN000001',to_date('11-MAY-23','DD-MON-RR'),'N06','NV03');
Insert into CHQTCSDL.PHIEUNHAP (MAPN,NGAYNHAP,MANCC,MANV) values ('PN13',to_date('12-MAY-23','DD-MON-RR'),'N06','NV08');
Insert into CHQTCSDL.PHIEUNHAP (MAPN,NGAYNHAP,MANCC,MANV) values ('PN000004',to_date('14-MAY-23','DD-MON-RR'),'N8','NV08');
REM INSERTING into CHQTCSDL.QUANTRI
SET DEFINE OFF;
Insert into CHQTCSDL.QUANTRI (MAQT,TAIKHOAN,MATKHAU,VAITRO) values ('QT01','anhduy14','E10ADC3949BA59ABBE56E057F20F883E','Admin');
Insert into CHQTCSDL.QUANTRI (MAQT,TAIKHOAN,MATKHAU,VAITRO) values ('QT02','mymy12','E10ADC3949BA59ABBE56E057F20F883E','Nh�n vi�n');
Insert into CHQTCSDL.QUANTRI (MAQT,TAIKHOAN,MATKHAU,VAITRO) values ('QT03','mydangiu','E10ADC3949BA59ABBE56E057F20F883E','Nh�n vi�n');
REM INSERTING into CHQTCSDL.SANPHAM
SET DEFINE OFF;
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP02','N?m kim chi H�n Qu?c',48,'B?ch',14900,'L01');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP04','B?p c?i tr�i tim Coop Select',17,'B?ch',28900,'L01');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP05','Rau th?m h?n h?p 100g',44,'G�i',11500,'L01');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP06','Rau t?n � 300g',13,'G�i',21500,'L01');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP07','Gi� ??u xanh 300g',52,'G�i',7600,'L01');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP08','H?t sen t??i 150g',33,'G�i',38500,'L01');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP09','Khoai t�y ?� L?t � kg',16,'Kg',24900,'L01');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP10','N?m ?�ng c� LTV 60g',19,'G�i',55400,'L01');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP11','T�o Envy M? nh? kg',39,'Kg',11500,'L02');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP12','D?a gi?ng MD2 ',17,'Kg',21500,'L02');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP13','B??i ???ng T�n Tri?u',52,'Kg',7600,'L02');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP14','D?a l??i HL ru?t cam',33,'Kg',38500,'L02');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP15','B??i ???ng l� cam',16,'Kg',24900,'L02');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP16','Nho xanh kh�ng h?t �c',22,'Kg',55400,'L02');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP17','?�i v?t 1/4 500g',10,'V?',11500,'L03');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP18','?c g� c�ng nghi?p 500g',10,'V?',21500,'L03');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP19','Ba r?i b� �c Fine Food',25,'V?',7600,'L03');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP21','?�i c�nh g� (c�nh t?i)',25,'V?',24900,'L03');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP22','M� ?�i g� BH 500g',33,'V?',55400,'L03');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP23','Tr?ng g� so',20,'V?',34000,'L03');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP24','Tr?ng g� kh�ng ph�',43,'H?p',30500,'L03');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP25','Tr?ng v?t b?c th?o',44,'V?',37900,'L03');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP26','Tr?ng g� ta ti?m',9,'H?p',34900,'L03');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP27','Tr?ng c�t Ba Hu�n v?',11,'V?',23100,'L03');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP28','Tr?ng g� Omega3 and DHA',12,'H?p',47500,'L03');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP29','B�n t??i 500g',18,'B?ch',8900,'L04');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP30','B�nh h?i 500g',16,'G�i',13000,'L04');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP31','B�nh ??t Ki?u Trang',19,'G�i',9500,'L04');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP32','Bu?n t??i Ba Kh�nh',27,'G�i',8900,'L04');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP33','H? ti?u t??i S�u Th?nh',20,'B?ch',11000,'L04');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP34','T�u h? tr?ng Ichiban',28,'C�i',9700,'L05');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP35','X�c x�ch Kebab La',16,'V?',57600,'L05');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP36','Ch? c� tr?ng c�t T�n Vi?t',29,'G�i',82500,'L05');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP37','G?o th?m ST25 l�a t�m',27,'B?ch',155000,'L05');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP38','C?i s� ?i?p size nh?',47,'B?ch',92000,'L05');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP39','Gh? Farci Coop Select',38,'V?',8800,'L05');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP40','Phomai Zott Toast',22,'G�i',56000,'L06');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP41','B? l?t t? nhi�n TH True',31,'G�i',62500,'L06');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP42','B�nh flan �NH H?NG',35,'H?p',75900,'L06');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP43','B? m?n Anchor',41,'G�i',112200,'L06');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP44','B? d?a VIETCOCO',51,'V?',37300,'L06');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP45','M?t d?a n??c Ocop',31,'Chai',99000,'L07');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP46','M?t ong r?ng s?a ch�a',22,'Chai',128500,'L07');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP47','N??c y?n s�o h?t chia',40,'L?c',50000,'L07');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP48','N??c y?n True Nest g?ng',31,'C�i',179500,'L07');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP49','N??c y?n s�o ?�ng tr�ng h? th?o',26,'L?c',31100,'L07');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP50','Y?n s�o collagen Green',27,'Chai',27000,'L07');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP000001','Tr� m?c h??ng',8,'G�i',13000,'L07');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('sp2','Tr� ?� L?nh',12,'Chai',15,'L07');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('sp1','Tr� ?�',2,'Chai',15000,'L07');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP000002','Tr� Atis�',40,'G�i',17000,'L07');
Insert into CHQTCSDL.SANPHAM (MASP,TENSP,SLTON,DVT,DONGIA,LOAISP) values ('SP026','Tr� Atis� ??',23,'Gam',23000,'L07');
--------------------------------------------------------
--  DDL for Index KHACHHANG_HOTENEMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHQTCSDL"."KHACHHANG_HOTENEMAIL" ON "CHQTCSDL"."KHACHHANG" ("HOTEN", "EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NHACUNGCAP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHQTCSDL"."NHACUNGCAP_PK" ON "CHQTCSDL"."NHACUNGCAP" ("MANCC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOAISANPHAM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHQTCSDL"."LOAISANPHAM_PK" ON "CHQTCSDL"."LOAISANPHAM" ("MALOAI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HOADON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHQTCSDL"."HOADON_PK" ON "CHQTCSDL"."HOADON" ("SOHD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SANPHAM_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHQTCSDL"."SANPHAM_UK1" ON "CHQTCSDL"."SANPHAM" ("TENSP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CTPN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHQTCSDL"."CTPN_PK" ON "CHQTCSDL"."CTPN" ("MAPN", "MASP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CTHD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHQTCSDL"."CTHD_PK" ON "CHQTCSDL"."CTHD" ("SOHD", "MASP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUANTRI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHQTCSDL"."QUANTRI_PK" ON "CHQTCSDL"."QUANTRI" ("MAQT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KHACHHANG_SDT
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHQTCSDL"."KHACHHANG_SDT" ON "CHQTCSDL"."KHACHHANG" ("SODT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUANTRI_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHQTCSDL"."QUANTRI_UNIQUE" ON "CHQTCSDL"."QUANTRI" ("TAIKHOAN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NHANVIEN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHQTCSDL"."NHANVIEN_PK" ON "CHQTCSDL"."NHANVIEN" ("MANV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KHACHHANG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHQTCSDL"."KHACHHANG_PK" ON "CHQTCSDL"."KHACHHANG" ("MAKH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SANPHAM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHQTCSDL"."SANPHAM_PK" ON "CHQTCSDL"."SANPHAM" ("MASP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PHIEUNHAP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHQTCSDL"."PHIEUNHAP_PK" ON "CHQTCSDL"."PHIEUNHAP" ("MAPN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_NGAYLV
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CHQTCSDL"."TRG_NGAYLV" 
BEFORE INSERT OR UPDATE ON NHANVIEN
FOR EACH ROW
BEGIN
  IF :NEW.NGAYLV > SYSDATE THEN
    RAISE_APPLICATION_ERROR(-20001, 'Ngay lam viec phai nho hon hoac bang ngay hien t?i!');
  END IF;
END;
/
ALTER TRIGGER "CHQTCSDL"."TRG_NGAYLV" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_NHANVIEN_TUOI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CHQTCSDL"."TRG_NHANVIEN_TUOI" 
BEFORE INSERT OR UPDATE ON NHANVIEN
FOR EACH ROW
DECLARE
    v_tuoi NUMBER;
BEGIN
    -- T�nh tu?i c?a nh�n vi�n
    v_tuoi := floor((SYSDATE - :NEW.NGAYSINH) / 365.25);
    IF v_tuoi < 18 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Tuoi khong hop le! Nhan vien phai >= 18 tuoi.');
    END IF;
END;
/
ALTER TRIGGER "CHQTCSDL"."TRG_NHANVIEN_TUOI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TUDONGTAOMAHD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CHQTCSDL"."TRG_TUDONGTAOMAHD" 
BEFORE INSERT ON HOADON
FOR EACH ROW
BEGIN
    SELECT 'HD' || TO_CHAR(seq_HoaDon.nextval, 'FM000000') INTO :new.SOHD FROM dual;
END;
/
ALTER TRIGGER "CHQTCSDL"."TRG_TUDONGTAOMAHD" DISABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TUDONGTAOMAKH
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CHQTCSDL"."TRG_TUDONGTAOMAKH" 
BEFORE INSERT ON KHACHHANG
FOR EACH ROW
BEGIN
    SELECT 'KH' || TO_CHAR(seq_KhachHang.nextval, 'FM000') INTO :new.MAKH FROM dual;
END;
/
ALTER TRIGGER "CHQTCSDL"."TRG_TUDONGTAOMAKH" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TUDONGTAOMAPN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CHQTCSDL"."TRG_TUDONGTAOMAPN" 
BEFORE INSERT ON PHIEUNHAP
FOR EACH ROW
BEGIN
    SELECT 'PN' || TO_CHAR(seq_PhieuNhap.nextval, 'FM000000') INTO :new.MAPN FROM dual;
END;
/
ALTER TRIGGER "CHQTCSDL"."TRG_TUDONGTAOMAPN" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TUDONGTAOMASP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CHQTCSDL"."TRG_TUDONGTAOMASP" 
BEFORE INSERT ON SANPHAM
FOR EACH ROW
BEGIN
    SELECT 'SP' || TO_CHAR(seq_SanPham.nextval, 'FM000') INTO :new.MASP FROM dual;
END;
/
ALTER TRIGGER "CHQTCSDL"."TRG_TUDONGTAOMASP" ENABLE;
--------------------------------------------------------
--  DDL for Procedure SP_CAPNHATCTHD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_CAPNHATCTHD" (
    V_SOHD IN VARCHAR2, 
    V_MASP IN VARCHAR2,
    V_SOLUONG_MOI NUMBER    
)
IS
    v_SOLUONG_CU CTHD.SOLUONG%TYPE;
BEGIN
    SAVEPOINT Begin_Tran;
    SELECT SOLUONG INTO v_SOLUONG_CU
    FROM CTHD
    WHERE SOHD = V_SOHD AND MASP = V_MASP;

    UPDATE CTHD
    SET  SOLUONG = V_SOLUONG_MOI
    WHERE SOHD = V_SOHD AND MASP = V_MASP;

    UPDATE SANPHAM
    SET SLTON = SLTON + v_SOLUONG_CU - V_SOLUONG_MOI
    WHERE MASP = V_MASP;

    BEGIN
      sp_UpdateTongTGHoaDon;
      SP_CAPNHAT_DOANHSO_KHACHHANG;
    EXCEPTION
      WHEN OTHERS THEN
        ROLLBACK TO Begin_Tran;
        RAISE_APPLICATION_ERROR(-20003, 'L?i khi c?p nh?t th�ng tin li�n quan ??n h�a ??n');
    END;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('C?p nh?t th�nh c�ng chi ti?t h�a ??n');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20003, 'C?p nh?t chi ti?t h�a ??n th?t b?i');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_CAPNHATCTHD" TO "ROLE_CHUCUAHANG";
  GRANT EXECUTE ON "CHQTCSDL"."SP_CAPNHATCTHD" TO "ROLE_NHANVIENBANHANG";
--------------------------------------------------------
--  DDL for Procedure SP_CAPNHATCTPN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_CAPNHATCTPN" (
    V_MAPN IN VARCHAR2, 
    V_MASP IN VARCHAR2,
    V_SOLUONG_MOI NUMBER    
)
IS
    v_SOLUONG_CU CTPN.SLNHAP%TYPE;
BEGIN
    SELECT SLNHAP INTO v_SOLUONG_CU
    FROM CTPN
    WHERE MAPN = V_MAPN AND MASP = V_MASP;

    UPDATE CTPN
    SET  SLNHAP = V_SOLUONG_MOI
    WHERE MAPN = V_MAPN AND MASP = V_MASP;

    UPDATE SANPHAM
    SET SLTON = SLTON + v_SOLUONG_CU - V_SOLUONG_MOI
    WHERE MASP = V_MASP;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Cap nhat thanh cong CTPN');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20003, 'Cap nhat CTPN that bai');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_CAPNHATCTPN" TO "ROLE_CHUCUAHANG";
  GRANT EXECUTE ON "CHQTCSDL"."SP_CAPNHATCTPN" TO "ROLE_NHANVIENNHAPHANG";
--------------------------------------------------------
--  DDL for Procedure SP_CAPNHATHOADON
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_CAPNHATHOADON" (
    v_SoHD HOADON.SOHD%TYPE,
    v_Ngay HOADON.NGAY%TYPE,
    v_MaKH HOADON.MAKH%TYPE,
    v_MaNV HOADON.MANV%TYPE,
    v_TongTG HOADON.TONGTG%TYPE
)
IS
BEGIN
    UPDATE HOADON
    SET  NGAY = v_Ngay, MAKH = v_MaKH, MANV = v_MaNV, TONGTG = v_TongTG
    WHERE SOHD = v_SoHD;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Cap nhat thanh cong hoa don so : ' || v_SoHD);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20003, 'Cap nhat hoa don that bai');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_CAPNHATHOADON" TO "ROLE_CHUCUAHANG";
  GRANT EXECUTE ON "CHQTCSDL"."SP_CAPNHATHOADON" TO "ROLE_NHANVIENBANHANG";
--------------------------------------------------------
--  DDL for Procedure SP_CAPNHATLOAISANPHAM
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_CAPNHATLOAISANPHAM" (
    v_MaLoai LOAISANPHAM.MALOAI%TYPE,
    v_TenLoai LOAISANPHAM.TENLOAI%TYPE
)
IS
BEGIN
    UPDATE LOAISANPHAM
    SET  TENLOAI = v_TenLoai
    WHERE MALOAI = v_MaLoai;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Cap nhat thanh cong loai sp: ' || v_TenLoai);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20003, 'Cap nhat loai san pham that bai');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_CAPNHATLOAISANPHAM" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Procedure SP_CAPNHATPHIEUNHAP
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_CAPNHATPHIEUNHAP" (
    V_MAPN PHIEUNHAP.MAPN%TYPE,
    V_NGAYNHAP PHIEUNHAP.NGAYNHAP%TYPE,
    V_MANCC PHIEUNHAP.MANCC%TYPE,
    V_MANV PHIEUNHAP.MANV%TYPE
)
IS
BEGIN
    UPDATE PHIEUNHAP
    SET  NGAYNHAP = V_NGAYNHAP, MANCC = V_MANCC, MANV = V_MANV
    WHERE MAPN = V_MAPN;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Cap nhat thanh cong phieu nhap : ' || V_MAPN);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20003, 'Cap nhat phieu nhap that bai');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_CAPNHATPHIEUNHAP" TO "ROLE_CHUCUAHANG";
  GRANT EXECUTE ON "CHQTCSDL"."SP_CAPNHATPHIEUNHAP" TO "ROLE_NHANVIENNHAPHANG";
--------------------------------------------------------
--  DDL for Procedure SP_CAPNHATSANPHAM
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_CAPNHATSANPHAM" (
    v_MaSP SANPHAM.MASP%TYPE,
    v_TenSP SANPHAM.TENSP%TYPE,
    v_SoLuong IN NUMBER,
    v_DonViTinh IN VARCHAR2,
    v_DonGia IN NUMBER,
    v_LoaiSP SANPHAM.LOAISP%TYPE
)
IS
    rangBuocMaSP int;
BEGIN
    SELECT COUNT(*) INTO rangBuocMaSP
    FROM LOAISANPHAM
    WHERE MALOAI = v_LoaiSP;

    IF rangBuocMaSP = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Khong ton tai loai san pham');
    END IF;
    UPDATE SANPHAM
    SET TENSP = v_TenSP, SLTON = v_SoLuong, DVT = v_DonViTinh, LOAISP = v_LoaiSP, DONGIA = v_DonGia
    WHERE MASP = v_MaSP;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Cap nhat thanh cong sp: ' || v_TenSP);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20003, 'Cap nhat san pham that bai');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_CAPNHATSANPHAM" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Procedure SP_CAPNHAT_DOANHSO_KHACHHANG
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_CAPNHAT_DOANHSO_KHACHHANG" 
IS
BEGIN
    UPDATE KHACHHANG KH
    SET KH.DOANHSO = (SELECT SUM(TONGTG)
        FROM HOADON HD
        WHERE HD.MAKH = KH.MAKH
        GROUP BY HD.MAKH);

    UPDATE KHACHHANG KH
    SET KH.DOANHSO = 0
    WHERE KH.MAKH NOT IN (SELECT HD.MAKH
        FROM HOADON HD
        WHERE HD.MAKH = KH.MAKH);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Cap nhat thanh cong!');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20003, 'Cap nhat that bai');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_CAPNHAT_DOANHSO_KHACHHANG" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Procedure SP_LAYDANHSACH_CTHD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_LAYDANHSACH_CTHD" (V_SOHD IN HOADON.SOHD%TYPE, o_cursor out SYS_REFCURSOR)
IS
BEGIN
    open o_cursor for
    SELECT * FROM CTHD WHERE SOHD = V_SOHD;
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_LAYDANHSACH_CTHD" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Procedure SP_LAYSPBANDUOCNHIEUNHAT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_LAYSPBANDUOCNHIEUNHAT" (X IN NUMBER)
AS
    v_tenvt SANPHAM.TENSP%TYPE;
    v_found NUMBER := 0;
    v_soluong NUMBER;
    CURSOR cur
    IS
        SELECT SANPHAM.TENSP, SUM(CTHD.SOLUONG)
        FROM SANPHAM
        JOIN CTHD ON CTHD.MASP = SANPHAM.MASP
        GROUP BY SANPHAM.TENSP
        ORDER BY SUM(CTHD.SOLUONG) DESC
        FETCH FIRST X ROWS ONLY;
BEGIN
    OPEN cur;
    LOOP
        FETCH cur INTO v_tenvt, v_soluong;
        EXIT WHEN cur%NOTFOUND;
        dbms_output.put_line('Ten san pham : '||v_tenvt || ' - ban duoc so luong: ' ||v_soluong);
        v_found := 1;
    END LOOP;
    CLOSE cur;

    IF v_found = 0 THEN
        dbms_output.put_line('Khong co vat tu nao!');
    END IF;
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_LAYSPBANDUOCNHIEUNHAT" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Procedure SP_MAHOAMATKHAU
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_MAHOAMATKHAU" (
  p_password IN QUANTRI.MATKHAU%TYPE,
  p_hashedPassword OUT QUANTRI.MATKHAU%TYPE
)
IS
BEGIN
  p_hashedPassword := DBMS_CRYPTO.HASH (
    UTL_I18N.STRING_TO_RAW(p_password, 'AL32UTF8'),
    DBMS_CRYPTO.HASH_MD5
  );
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_MAHOAMATKHAU" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Procedure SP_THEMCTHD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_THEMCTHD" (
    V_SOHD CTHD.SOHD%TYPE,
    V_MASP CTHD.MASP%TYPE,
    V_SOLUONG CTHD.SOLUONG%TYPE
)
IS
    v_DONGIA SANPHAM.DONGIA%TYPE;
BEGIN
    SAVEPOINT Begin_Tran;
    SELECT (DONGIA + DONGIA * 0.1) INTO v_DONGIA
    FROM SANPHAM
    WHERE MASP = V_MASP;

    INSERT INTO CTHD(SOHD, MASP, DONGIA, SOLUONG) 
    VALUES(V_SOHD, V_MASP, v_DONGIA, V_SOLUONG);

    UPDATE SANPHAM
    SET SLTON = SLTON - V_SOLUONG
    WHERE MASP = V_MASP;
    BEGIN
      sp_UpdateTongTGHoaDon;
      SP_CAPNHAT_DOANHSO_KHACHHANG;
    EXCEPTION
      WHEN OTHERS THEN
        ROLLBACK TO Begin_Tran;
        RAISE_APPLICATION_ERROR(-20003, 'L?i khi c?p nh?t th�ng tin li�n quan ??n h�a ??n');
    END;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Them thanh cong chi tiet hoa don: ' || V_SOHD);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20003, 'Them chi tiet hoa don that bai');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_THEMCTHD" TO "ROLE_CHUCUAHANG";
  GRANT EXECUTE ON "CHQTCSDL"."SP_THEMCTHD" TO "ROLE_NHANVIENBANHANG";
--------------------------------------------------------
--  DDL for Procedure SP_THEMCTPN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_THEMCTPN" (
    V_MAPN CTPN.MAPN%TYPE,
    V_MASP CTPN.MASP%TYPE,
    V_SLNHAP CTPN.SLNHAP%TYPE,
    V_DONGIANHAP CTPN.DONGIANHAP%TYPE
)
IS
    v_SLTON SANPHAM.SLTON%TYPE;
BEGIN
    SELECT SLTON INTO v_SLTON
    FROM SANPHAM
    WHERE MASP = V_MASP;

    INSERT INTO CTPN(MAPN, MASP, SLNHAP, DONGIANHAP) 
    VALUES(V_MAPN, V_MASP, V_SLNHAP, V_DONGIANHAP);

    UPDATE SANPHAM
    SET SLTON = SLTON + V_SLNHAP
    WHERE MASP = V_MASP;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Them thanh cong chi tiet phieu nhap: ' || V_MAPN);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20003, 'Them chi tiet phieu nhap that bai');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_THEMCTPN" TO "ROLE_CHUCUAHANG";
  GRANT EXECUTE ON "CHQTCSDL"."SP_THEMCTPN" TO "ROLE_NHANVIENNHAPHANG";
--------------------------------------------------------
--  DDL for Procedure SP_THEMHOADON
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_THEMHOADON" (
    v_MaKH HOADON.MAKH%TYPE,
    v_MaNV HOADON.MANV%TYPE
)
AS
    V_MASP SANPHAM.MASP%TYPE;
BEGIN
    SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
    DBMS_SESSION.SLEEP(10); -- T?m d?ng th?c thi trong 5 gi�y
    SELECT 'HD' || TO_CHAR(seq_HoaDon.nextval, 'FM000000') INTO V_MASP FROM DUAL;
    INSERT INTO HOADON(SOHD, NGAY, MAKH, MANV, TONGTG) 
    VALUES(V_MASP, TRUNC(SYSDATE), v_MaKH, v_MaNV, 0);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Them thanh cong hoa don');

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20003, 'Them hoa don that bai');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_THEMHOADON" TO "ROLE_CHUCUAHANG";
  GRANT EXECUTE ON "CHQTCSDL"."SP_THEMHOADON" TO "ROLE_NHANVIENBANHANG";
--------------------------------------------------------
--  DDL for Procedure SP_THEMLOAISANPHAM
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_THEMLOAISANPHAM" (
    v_MaLoai LOAISANPHAM.MALOAI%TYPE,
    v_TenLoai LOAISANPHAM.TENLOAI%TYPE
)
IS
BEGIN
    INSERT INTO LOAISANPHAM(MALOAI, TENLOAI) 
    VALUES(v_MaLoai,v_TenLoai);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('them thanh cong loai san pham: ' || v_TenLoai);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20003, 'Them loai san pham pham that bai');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_THEMLOAISANPHAM" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Procedure SP_THEMPHIEUNHAP
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_THEMPHIEUNHAP" (
    V_MANCC PHIEUNHAP.MANCC%TYPE,
    V_MANV PHIEUNHAP.MANV%TYPE
)
IS
BEGIN
    SET TRANSACTION ISOLATION LEVEL SERIALIZABLE; 
    INSERT INTO PHIEUNHAP(MAPN, NGAYNHAP, MANCC, MANV) 
    VALUES(NULL, TRUNC(SYSDATE), v_MANCC, V_MANV);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Them thanh phieu nhap: ');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20003, 'Them phieu nhap that bai');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_THEMPHIEUNHAP" TO "ROLE_CHUCUAHANG";
  GRANT EXECUTE ON "CHQTCSDL"."SP_THEMPHIEUNHAP" TO "ROLE_NHANVIENNHAPHANG";
--------------------------------------------------------
--  DDL for Procedure SP_THEMSANPHAM
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_THEMSANPHAM" (
    v_TenSP SANPHAM.TENSP%TYPE,
    v_SoLuong IN NUMBER,
    v_DonViTinh IN VARCHAR2,
    v_DonGia IN NUMBER,
    v_LoaiSP SANPHAM.LOAISP%TYPE
)
IS
    rangBuocMaSP int;
BEGIN
    SET TRANSACTION ISOLATION LEVEL SERIALIZABLE; 
    SELECT COUNT(*) INTO rangBuocMaSP
    FROM LOAISANPHAM
    WHERE MALOAI = v_LoaiSP;

    IF rangBuocMaSP = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Khong ton tai loai san pham');
    END IF;
    INSERT INTO SANPHAM(MASP, TENSP, SLTON, DVT, DONGIA, LOAISP) 
    VALUES(null,v_TenSP,v_SoLuong,v_DonViTinh,v_DonGia, v_LoaiSP);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('them thanh cong sp: ');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20003, 'Them san pham that bai');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_THEMSANPHAM" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Procedure SP_TINHLAIXUATCUASANPHAM
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_TINHLAIXUATCUASANPHAM" 
IS
BEGIN
   FOR sp IN (SELECT MASP, TENSP, FUNC_SoLuongSanPhamBanDuoc(MASP) as soluong, func_TinhLaiCuaSP(MASP) as laixuat FROM SANPHAM)
   LOOP
      DBMS_OUTPUT.PUT_LINE('Ma san pham: ' || sp.MASP || ', Ten san pham: ' || sp.TENSP || ', So luong: ' || sp.soluong || ', Lai xuat: ' || sp.laixuat);
   END LOOP;
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_TINHLAIXUATCUASANPHAM" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Procedure SP_UPDATEDONGIACTHD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_UPDATEDONGIACTHD" 
IS
BEGIN
  UPDATE CTHD 
  SET DONGIA = (SELECT DONGIA + (DONGIA * 20/100) 
               FROM SANPHAM 
               WHERE SANPHAM.MASP = CTHD.MASP);
  COMMIT;
  BEGIN
    SP_CAPNHAT_DOANHSO_KHACHHANG;
    sp_UpdateTongTGHoaDon;
  END;
  DBMS_OUTPUT.PUT_LINE('C?p nh?t DONGIA cho CTHD th�nh c�ng');
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Kh�ng t�m th?y s?n ph?m t??ng ?ng trong b?ng SANPHAM');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('L?i khi c?p nh?t DONGIA cho CTHD');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_UPDATEDONGIACTHD" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Procedure SP_UPDATETONGTGHOADON
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_UPDATETONGTGHOADON" 
AS
BEGIN
  UPDATE HOADON
  SET TONGTG = (
    SELECT SUM(CTHD.SOLUONG * CTHD.DONGIA)
    FROM CTHD
    WHERE CTHD.SOHD = HOADON.SOHD
  );
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('C?p nh?t TONGTG cho HOADON th�nh c�ng');
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Kh�ng t�m th?y h�a ??n t??ng ?ng trong b?ng HOADON');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('L?i khi c?p nh?t TONGTG cho HOADON');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_UPDATETONGTGHOADON" TO "CHUCUAHANG";
--------------------------------------------------------
--  DDL for Procedure SP_UPDATE_TRIGIA_HD_CTHD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_UPDATE_TRIGIA_HD_CTHD" 
AS
BEGIN
    SP_UPDATETONGTGHOADON;
    SP_UPDATEDONGIACTHD;
    SP_CAPNHAT_DOANHSO_KHACHHANG;
END;

/
--------------------------------------------------------
--  DDL for Procedure SP_XOACTHD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_XOACTHD" (V_SOHD IN VARCHAR2, V_MASP IN VARCHAR2)
IS
    V_SOLUONG INT;
BEGIN
    SAVEPOINT Begin_Tran;
    SELECT SOLUONG INTO V_SOLUONG
    FROM CTHD WHERE SOHD = V_SOHD AND MASP = V_MASP;

    DELETE FROM CTHD 
    WHERE SOHD = V_SOHD AND MASP = V_MASP;

    UPDATE SANPHAM
    SET SLTON = SLTON + V_SOLUONG
    WHERE MASP = V_MASP;
    BEGIN
      sp_UpdateTongTGHoaDon;
      SP_CAPNHAT_DOANHSO_KHACHHANG;
    EXCEPTION
      WHEN OTHERS THEN
        ROLLBACK TO Begin_Tran;
        RAISE_APPLICATION_ERROR(-20003, 'L?i khi c?p nh?t th�ng tin li�n quan ??n h�a ??n');
    END;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20002, 'Loi khi xoa cthd!');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_XOACTHD" TO "ROLE_CHUCUAHANG";
  GRANT EXECUTE ON "CHQTCSDL"."SP_XOACTHD" TO "ROLE_NHANVIENBANHANG";
--------------------------------------------------------
--  DDL for Procedure SP_XOACTPN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_XOACTPN" (V_MAPN IN VARCHAR2, V_MASP IN VARCHAR2)
IS
    V_SOLUONG INT;
BEGIN
    SELECT SLNHAP INTO V_SOLUONG
    FROM CTPN WHERE MAPN = V_MAPN AND MASP = V_MASP;

    DELETE FROM CTPN 
    WHERE MAPN = V_MAPN AND MASP = V_MASP;

    UPDATE SANPHAM
    SET SLTON = SLTON - V_SOLUONG
    WHERE MASP = V_MASP;
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20002, 'Loi khi xoa ctpn!');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_XOACTPN" TO "ROLE_CHUCUAHANG";
  GRANT EXECUTE ON "CHQTCSDL"."SP_XOACTPN" TO "ROLE_NHANVIENNHAPHANG";
--------------------------------------------------------
--  DDL for Procedure SP_XOAHOADON
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_XOAHOADON" (v_SoHD IN VARCHAR2)
IS
    v_count int;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM HOADON
    WHERE SOHD = v_SoHD;
    IF v_count > 0 THEN
        DELETE FROM HOADON WHERE SOHD = v_SoHD;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Xoa hoa don thanh cong!');
    ELSE
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001, 'khong ton tai so hoa don!');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20002, 'Loi khi xoa hoa don!');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_XOAHOADON" TO "ROLE_CHUCUAHANG";
  GRANT EXECUTE ON "CHQTCSDL"."SP_XOAHOADON" TO "ROLE_NHANVIENBANHANG";
--------------------------------------------------------
--  DDL for Procedure SP_XOALOAISANPHAM
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_XOALOAISANPHAM" (v_MaLoai IN VARCHAR2)
IS
    v_count int;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM LOAISANPHAM
    WHERE MALOAI = v_MaLoai;
    IF v_count > 0 THEN
        DELETE FROM LOAISANPHAM WHERE MALOAI = v_MaLoai;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Xoa loai san pham thanh cong!');
    ELSE
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001, 'Khong ton tai ma loai san pham tren!');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20002, 'Loi khi xoa loai san pham!');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_XOALOAISANPHAM" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Procedure SP_XOAPHIEUNHAP
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_XOAPHIEUNHAP" (V_MAPN IN VARCHAR2)
IS
    v_count int;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM PHIEUNHAP
    WHERE MAPN = V_MAPN;
    IF v_count > 0 THEN
        DELETE FROM PHIEUNHAP WHERE MAPN = V_MAPN;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Xoa phieu nhap thanh cong!');
    ELSE
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001, 'khong ton tai ma phieu nhap!');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20002, 'Loi khi xoa phieu nhap!');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_XOAPHIEUNHAP" TO "ROLE_CHUCUAHANG";
  GRANT EXECUTE ON "CHQTCSDL"."SP_XOAPHIEUNHAP" TO "ROLE_NHANVIENNHAPHANG";
--------------------------------------------------------
--  DDL for Procedure SP_XOASANPHAM
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHQTCSDL"."SP_XOASANPHAM" (v_MaSP IN VARCHAR2)
IS
    v_count int;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM SANPHAM
    WHERE MASP = v_MaSP;
    IF v_count > 0 THEN
        DELETE FROM SANPHAM WHERE MASP = v_MaSP;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Xoa san pham thanh cong!');
    ELSE
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20003, 'Khong ton tai ma san pham tren!');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20003, 'Loi khi xoa san pham!');
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."SP_XOASANPHAM" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Package PKG_HOATDONG_NHANVIEN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "CHQTCSDL"."PKG_HOATDONG_NHANVIEN" 
IS
    FUNCTION FUNC_SOHD (V_MANV IN NHANVIEN.MANV%TYPE)
        RETURN NUMBER;

    FUNCTION FUNC_SOPN (V_MANV IN NHANVIEN.MANV%TYPE)
        RETURN NUMBER;

    FUNCTION FUNC_DOANHTHU (V_MANV IN NHANVIEN.MANV%TYPE)
        RETURN NUMBER;
END;

/
--------------------------------------------------------
--  DDL for Package Body PKG_HOATDONG_NHANVIEN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "CHQTCSDL"."PKG_HOATDONG_NHANVIEN" 
IS
    FUNCTION FUNC_SOHD (V_MANV IN NHANVIEN.MANV%TYPE)
        RETURN NUMBER
    IS
        v_tonghoadon NUMBER := 0;
    BEGIN
        SELECT COUNT(*) INTO v_tonghoadon
        FROM HOADON
        WHERE MANV = V_MANV
        GROUP BY MANV;

        IF v_tonghoadon IS NULL THEN 
            v_tonghoadon := 0; 
        END IF;
        RETURN v_tonghoadon;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 0;
    END FUNC_SOHD;

    FUNCTION FUNC_SOPN (V_MANV IN NHANVIEN.MANV%TYPE)
        RETURN NUMBER
    IS
        v_tongPhieuNhap NUMBER := 0;
    BEGIN
        SELECT COUNT(*) INTO v_tongPhieuNhap
        FROM PHIEUNHAP
        WHERE MANV = V_MANV
        GROUP BY MANV;

        IF v_tongPhieuNhap IS NULL THEN 
            v_tongPhieuNhap := 0; 
        END IF;
        RETURN v_tongPhieuNhap;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 0;
    END FUNC_SOPN;

    FUNCTION FUNC_DOANHTHU (V_MANV IN NHANVIEN.MANV%TYPE)
        RETURN NUMBER
    IS
        v_tongDoanhThu NUMBER := 0;
    BEGIN
        SELECT SUM(TONGTG) INTO v_tongDoanhThu
        FROM HOADON
        WHERE MANV = V_MANV
        GROUP BY MANV;

        RETURN v_tongDoanhThu;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 0;
    END FUNC_DOANHTHU;
END;

/
--------------------------------------------------------
--  DDL for Function FUNC_DEMSOHOADONCUAKH
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHQTCSDL"."FUNC_DEMSOHOADONCUAKH" (p_makh IN KHACHHANG.MAKH%TYPE)
    RETURN NUMBER
IS
    v_tonghoadon NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_tonghoadon
    FROM HOADON
    WHERE MAKH = p_makh
    GROUP BY MAKH;

    IF v_tonghoadon IS NULL THEN 
        v_tonghoadon := 0; 
    END IF;
    RETURN v_tonghoadon;
EXCEPTION
    WHEN OTHERS THEN
        RETURN 0;
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."FUNC_DEMSOHOADONCUAKH" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Function FUNC_DEMSOHOADON_NHANVIEN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHQTCSDL"."FUNC_DEMSOHOADON_NHANVIEN" (V_MANV IN NHANVIEN.MANV%TYPE)
    RETURN NUMBER
IS
    v_tonghoadon NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_tonghoadon
    FROM HOADON
    WHERE MANV = V_MANV
    GROUP BY MANV;

    IF v_tonghoadon IS NULL THEN 
        v_tonghoadon := 0; 
    END IF;
    RETURN v_tonghoadon;
EXCEPTION
    WHEN OTHERS THEN
        RETURN 0;
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."FUNC_DEMSOHOADON_NHANVIEN" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Function FUNC_DEMSOLUONGSP_CTPN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHQTCSDL"."FUNC_DEMSOLUONGSP_CTPN" (V_MASP IN SANPHAM.MASP%TYPE)
    RETURN NUMBER
IS
    V_SOLUONG NUMBER := 0;
BEGIN
    SELECT SUM(SLNHAP) INTO V_SOLUONG
    FROM CTPN
    WHERE MASP = V_MASP
    GROUP BY MASP;

    RETURN V_SOLUONG;
EXCEPTION
    WHEN OTHERS THEN
        RETURN 0;
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."FUNC_DEMSOLUONGSP_CTPN" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Function FUNC_DEMSOPHIEUNHAP_NHANVIEN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHQTCSDL"."FUNC_DEMSOPHIEUNHAP_NHANVIEN" (V_MANV IN NHANVIEN.MANV%TYPE)
    RETURN NUMBER
IS
    v_tongPhieuNhap NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_tongPhieuNhap
    FROM PHIEUNHAP
    WHERE MANV = V_MANV
    GROUP BY MANV;

    IF v_tongPhieuNhap IS NULL THEN 
        v_tongPhieuNhap := 0; 
    END IF;
    RETURN v_tongPhieuNhap;
EXCEPTION
    WHEN OTHERS THEN
        RETURN 0;
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."FUNC_DEMSOPHIEUNHAP_NHANVIEN" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Function FUNC_SOLUONGSANPHAMBANDUOC
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHQTCSDL"."FUNC_SOLUONGSANPHAMBANDUOC" (v_MaSP IN VARCHAR2)
RETURN INT
IS
   v_SoLuong INT := 0;
BEGIN
   SELECT SUM(ct.SOLUONG)
   INTO v_SoLuong
   FROM CTHD ct
   JOIN HOADON hd ON ct.SOHD = hd.SOHD
   WHERE ct.MASP = v_MaSP;

   RETURN NVL(v_SoLuong, 0);
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      RETURN 0;
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."FUNC_SOLUONGSANPHAMBANDUOC" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Function FUNC_TINHDOANHTHU_NHANVIEN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHQTCSDL"."FUNC_TINHDOANHTHU_NHANVIEN" (V_MANV IN NHANVIEN.MANV%TYPE)
    RETURN NUMBER
IS
    v_tongDoanhThu NUMBER := 0;
BEGIN
    SELECT SUM(TONGTG) INTO v_tongDoanhThu
    FROM HOADON
    WHERE MANV = V_MANV
    GROUP BY MANV;

    RETURN v_tongDoanhThu;
EXCEPTION
    WHEN OTHERS THEN
        RETURN 0;
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."FUNC_TINHDOANHTHU_NHANVIEN" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Function FUNC_TINHLAI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHQTCSDL"."FUNC_TINHLAI" (v_MaSP VARCHAR2 DEFAULT NULL)
RETURN NUMBER
IS
   v_LaiSuat NUMBER := 0;
BEGIN
    IF v_MaSP IS NOT NULL THEN
        SELECT SUM((CT.DONGIA - VT.DONGIA) * CT.SOLUONG) INTO v_LaiSuat
        FROM CTHD CT JOIN SANPHAM VT ON CT.MASP = VT.MASP
        WHERE CT.MASP = v_MaSP;
    ELSE
        SELECT SUM((CT.DONGIA - VT.DONGIA) * CT.SOLUONG) INTO v_LaiSuat
        FROM CTHD CT JOIN SANPHAM VT ON CT.MASP = VT.MASP;
    END IF;

   RETURN v_LaiSuat;
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."FUNC_TINHLAI" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  DDL for Function FUNC_TINHLAICUASP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHQTCSDL"."FUNC_TINHLAICUASP" (v_MaSP IN VARCHAR2)
RETURN NUMBER
IS
   v_LaiSuat NUMBER := 0;
BEGIN
   SELECT SUM((ct.DONGIA - vt.DONGIA) * ct.SOLUONG)
   INTO v_LaiSuat
   FROM CTHD ct
   JOIN SANPHAM vt ON ct.MASP = vt.MASP
   WHERE ct.MASP = v_MaSP;

   RETURN NVL(v_LaiSuat, 0);
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      RETURN 0;
END;

/

  GRANT EXECUTE ON "CHQTCSDL"."FUNC_TINHLAICUASP" TO "ROLE_CHUCUAHANG";
--------------------------------------------------------
--  Constraints for Table NHACUNGCAP
--------------------------------------------------------

  ALTER TABLE "CHQTCSDL"."NHACUNGCAP" MODIFY ("MANCC" NOT NULL ENABLE);
  ALTER TABLE "CHQTCSDL"."NHACUNGCAP" ADD CONSTRAINT "NHACUNGCAP_PK" PRIMARY KEY ("MANCC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SANPHAM
--------------------------------------------------------

  ALTER TABLE "CHQTCSDL"."SANPHAM" MODIFY ("MASP" NOT NULL ENABLE);
  ALTER TABLE "CHQTCSDL"."SANPHAM" ADD CONSTRAINT "SANPHAM_PK" PRIMARY KEY ("MASP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHQTCSDL"."SANPHAM" ADD CONSTRAINT "SANPHAM_UNIQUE" UNIQUE ("TENSP")
  USING INDEX (CREATE UNIQUE INDEX "CHQTCSDL"."SANPHAM_UK1" ON "CHQTCSDL"."SANPHAM" ("TENSP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "CHQTCSDL"."SANPHAM" ADD CONSTRAINT "SANPHAM_SLTON" CHECK (SLTON >= 0) ENABLE;
  ALTER TABLE "CHQTCSDL"."SANPHAM" ADD CONSTRAINT "SANPHAM_DONGIA" CHECK (DONGIA > 0) ENABLE;
--------------------------------------------------------
--  Constraints for Table HOADON
--------------------------------------------------------

  ALTER TABLE "CHQTCSDL"."HOADON" MODIFY ("SOHD" NOT NULL ENABLE);
  ALTER TABLE "CHQTCSDL"."HOADON" ADD CONSTRAINT "HOADON_PK" PRIMARY KEY ("SOHD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QUANTRI
--------------------------------------------------------

  ALTER TABLE "CHQTCSDL"."QUANTRI" MODIFY ("MAQT" NOT NULL ENABLE);
  ALTER TABLE "CHQTCSDL"."QUANTRI" ADD CONSTRAINT "QUANTRI_PK" PRIMARY KEY ("MAQT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHQTCSDL"."QUANTRI" MODIFY ("TAIKHOAN" NOT NULL ENABLE);
  ALTER TABLE "CHQTCSDL"."QUANTRI" MODIFY ("MATKHAU" NOT NULL ENABLE);
  ALTER TABLE "CHQTCSDL"."QUANTRI" ADD CONSTRAINT "QUANTRI_UNIQUE" UNIQUE ("TAIKHOAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PHIEUNHAP
--------------------------------------------------------

  ALTER TABLE "CHQTCSDL"."PHIEUNHAP" MODIFY ("MAPN" NOT NULL ENABLE);
  ALTER TABLE "CHQTCSDL"."PHIEUNHAP" ADD CONSTRAINT "PHIEUNHAP_PK" PRIMARY KEY ("MAPN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CTHD
--------------------------------------------------------

  ALTER TABLE "CHQTCSDL"."CTHD" MODIFY ("SOHD" NOT NULL ENABLE);
  ALTER TABLE "CHQTCSDL"."CTHD" MODIFY ("MASP" NOT NULL ENABLE);
  ALTER TABLE "CHQTCSDL"."CTHD" ADD CONSTRAINT "CTHD_PK" PRIMARY KEY ("SOHD", "MASP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NHANVIEN
--------------------------------------------------------

  ALTER TABLE "CHQTCSDL"."NHANVIEN" MODIFY ("MANV" NOT NULL ENABLE);
  ALTER TABLE "CHQTCSDL"."NHANVIEN" ADD CONSTRAINT "NHANVIEN_PK" PRIMARY KEY ("MANV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHQTCSDL"."NHANVIEN" ADD CONSTRAINT "NHANVIEN_CHK1" CHECK (NGAYSINH < NGAYLV) ENABLE;
  ALTER TABLE "CHQTCSDL"."NHANVIEN" ADD CONSTRAINT "NHANVIEN_GIOITINH" CHECK (GIOITINH IN ('Nam', u'N\1eef')) ENABLE;
--------------------------------------------------------
--  Constraints for Table LOAISANPHAM
--------------------------------------------------------

  ALTER TABLE "CHQTCSDL"."LOAISANPHAM" MODIFY ("MALOAI" NOT NULL ENABLE);
  ALTER TABLE "CHQTCSDL"."LOAISANPHAM" ADD CONSTRAINT "LOAISANPHAM_PK" PRIMARY KEY ("MALOAI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHQTCSDL"."LOAISANPHAM" MODIFY ("TENLOAI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KHACHHANG
--------------------------------------------------------

  ALTER TABLE "CHQTCSDL"."KHACHHANG" MODIFY ("MAKH" NOT NULL ENABLE);
  ALTER TABLE "CHQTCSDL"."KHACHHANG" ADD CONSTRAINT "KHACHHANG_PK" PRIMARY KEY ("MAKH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHQTCSDL"."KHACHHANG" ADD CONSTRAINT "KHACHHANG_SDT" UNIQUE ("SODT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHQTCSDL"."KHACHHANG" ADD CONSTRAINT "KHACHHANG_HOTENEMAIL" UNIQUE ("HOTEN", "EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CTPN
--------------------------------------------------------

  ALTER TABLE "CHQTCSDL"."CTPN" MODIFY ("MAPN" NOT NULL ENABLE);
  ALTER TABLE "CHQTCSDL"."CTPN" MODIFY ("MASP" NOT NULL ENABLE);
  ALTER TABLE "CHQTCSDL"."CTPN" ADD CONSTRAINT "CTPN_PK" PRIMARY KEY ("MAPN", "MASP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CTHD
--------------------------------------------------------

  ALTER TABLE "CHQTCSDL"."CTHD" ADD CONSTRAINT "CTHD_HOADON_FK" FOREIGN KEY ("SOHD")
	  REFERENCES "CHQTCSDL"."HOADON" ("SOHD") ENABLE;
  ALTER TABLE "CHQTCSDL"."CTHD" ADD CONSTRAINT "CTHD_SANPHAM_FK" FOREIGN KEY ("MASP")
	  REFERENCES "CHQTCSDL"."SANPHAM" ("MASP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CTPN
--------------------------------------------------------

  ALTER TABLE "CHQTCSDL"."CTPN" ADD CONSTRAINT "CTPN_FK1" FOREIGN KEY ("MASP")
	  REFERENCES "CHQTCSDL"."SANPHAM" ("MASP") ENABLE;
  ALTER TABLE "CHQTCSDL"."CTPN" ADD CONSTRAINT "CTPN_PHIEUNHAP" FOREIGN KEY ("MAPN")
	  REFERENCES "CHQTCSDL"."PHIEUNHAP" ("MAPN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HOADON
--------------------------------------------------------

  ALTER TABLE "CHQTCSDL"."HOADON" ADD CONSTRAINT "HOADON_KHACHHANG_FK" FOREIGN KEY ("MAKH")
	  REFERENCES "CHQTCSDL"."KHACHHANG" ("MAKH") ON DELETE CASCADE ENABLE;
  ALTER TABLE "CHQTCSDL"."HOADON" ADD CONSTRAINT "HOADON_NHANVIEN_FK" FOREIGN KEY ("MANV")
	  REFERENCES "CHQTCSDL"."NHANVIEN" ("MANV") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PHIEUNHAP
--------------------------------------------------------

  ALTER TABLE "CHQTCSDL"."PHIEUNHAP" ADD CONSTRAINT "PHIEUNHAP_NHACC" FOREIGN KEY ("MANCC")
	  REFERENCES "CHQTCSDL"."NHACUNGCAP" ("MANCC") ENABLE;
  ALTER TABLE "CHQTCSDL"."PHIEUNHAP" ADD CONSTRAINT "PHIEUNHAP_NHANVIEN" FOREIGN KEY ("MANV")
	  REFERENCES "CHQTCSDL"."NHANVIEN" ("MANV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SANPHAM
--------------------------------------------------------

  ALTER TABLE "CHQTCSDL"."SANPHAM" ADD CONSTRAINT "SANPHAM_LOAISP_FK" FOREIGN KEY ("LOAISP")
	  REFERENCES "CHQTCSDL"."LOAISANPHAM" ("MALOAI") ENABLE;
